  // Mock transactions data
  export const mockTransactions = [
    {
      _id: "txn_1",
      transactionId: "TXN-2023-10-01-001",
      type: "purchase",
      amount: 129.99,
      fee: 3.99,
      status: "completed",
      date: "2023-10-01T10:15:00.000Z",
      customer: {
        name: "John Doe",
        email: "john.doe@example.com",
      },
      product: {
        name: "Premium Headphones",
        id: "prod_001",
      },
      paymentMethod: "credit_card",
    },
    {
      _id: "txn_2",
      transactionId: "TXN-2023-10-02-002",
      type: "purchase",
      amount: 49.99,
      fee: 1.5,
      status: "completed",
      date: "2023-10-02T14:30:00.000Z",
      customer: {
        name: "Jane Smith",
        email: "jane.smith@example.com",
      },
      product: {
        name: "Wireless Mouse",
        id: "prod_002",
      },
      paymentMethod: "paypal",
    },
    {
      _id: "txn_3",
      transactionId: "TXN-2023-10-03-003",
      type: "refund",
      amount: 49.99,
      fee: 0,
      status: "completed",
      date: "2023-10-03T09:45:00.000Z",
      customer: {
        name: "Jane Smith",
        email: "jane.smith@example.com",
      },
      product: {
        name: "Wireless Mouse",
        id: "prod_002",
      },
      paymentMethod: "paypal",
    },
    {
      _id: "txn_4",
      transactionId: "TXN-2023-10-04-004",
      type: "withdrawal",
      amount: 500.0,
      fee: 5.0,
      status: "completed",
      date: "2023-10-04T16:20:00.000Z",
      customer: {
        name: "Seller Account",
        email: "seller@example.com",
      },
      product: null,
      paymentMethod: "bank_transfer",
    },
    {
      _id: "txn_5",
      transactionId: "TXN-2023-10-05-005",
      type: "purchase",
      amount: 199.99,
      fee: 5.99,
      status: "pending",
      date: "2023-10-05T11:10:00.000Z",
      customer: {
        name: "Robert Johnson",
        email: "robert.j@example.com",
      },
      product: {
        name: "Smart Watch",
        id: "prod_003",
      },
      paymentMethod: "credit_card",
    },
    {
      _id: "txn_6",
      transactionId: "TXN-2023-10-06-006",
      type: "deposit",
      amount: 1000.0,
      fee: 0,
      status: "completed",
      date: "2023-10-06T13:25:00.000Z",
      customer: {
        name: "Seller Account",
        email: "seller@example.com",
      },
      product: null,
      paymentMethod: "bank_transfer",
    },
    {
      _id: "txn_7",
      transactionId: "TXN-2023-10-07-007",
      type: "fee",
      amount: 25.0,
      fee: 0,
      status: "completed",
      date: "2023-10-07T09:00:00.000Z",
      customer: {
        name: "Marketplace",
        email: "admin@marketplace.com",
      },
      product: null,
      paymentMethod: "system",
    },
    {
      _id: "txn_8",
      transactionId: "TXN-2023-10-08-008",
      type: "purchase",
      amount: 79.99,
      fee: 2.49,
      status: "failed",
      date: "2023-10-08T15:40:00.000Z",
      customer: {
        name: "Michael Brown",
        email: "michael.b@example.com",
      },
      product: {
        name: "Bluetooth Speaker",
        id: "prod_004",
      },
      paymentMethod: "credit_card",
    },
    {
      _id: "txn_9",
      transactionId: "TXN-2023-10-09-009",
      type: "purchase",
      amount: 149.99,
      fee: 4.5,
      status: "completed",
      date: "2023-10-09T12:15:00.000Z",
      customer: {
        name: "Emily Davis",
        email: "emily.d@example.com",
      },
      product: {
        name: "External Hard Drive",
        id: "prod_005",
      },
      paymentMethod: "paypal",
    },
    {
      _id: "txn_10",
      transactionId: "TXN-2023-10-10-010",
      type: "refund",
      amount: 79.99,
      fee: 0,
      status: "processing",
      date: "2023-10-10T10:30:00.000Z",
      customer: {
        name: "Michael Brown",
        email: "michael.b@example.com",
      },
      product: {
        name: "Bluetooth Speaker",
        id: "prod_004",
      },
      paymentMethod: "credit_card",
    },
    {
      _id: "txn_11",
      transactionId: "TXN-2023-10-11-011",
      type: "purchase",
      amount: 299.99,
      fee: 8.99,
      status: "completed",
      date: "2023-10-11T14:20:00.000Z",
      customer: {
        name: "Sarah Wilson",
        email: "sarah.w@example.com",
      },
      product: {
        name: "Tablet",
        id: "prod_006",
      },
      paymentMethod: "credit_card",
    },
    {
      _id: "txn_12",
      transactionId: "TXN-2023-10-12-012",
      type: "withdrawal",
      amount: 750.0,
      fee: 7.5,
      status: "pending",
      date: "2023-10-12T16:45:00.000Z",
      customer: {
        name: "Seller Account",
        email: "seller@example.com",
      },
      product: null,
      paymentMethod: "bank_transfer",
    },
    {
      _id: "txn_13",
      transactionId: "TXN-2023-10-13-013",
      type: "purchase",
      amount: 59.99,
      fee: 1.8,
      status: "completed",
      date: "2023-10-13T11:05:00.000Z",
      customer: {
        name: "David Miller",
        email: "david.m@example.com",
      },
      product: {
        name: "Gaming Mouse",
        id: "prod_007",
      },
      paymentMethod: "paypal",
    },
    {
      _id: "txn_14",
      transactionId: "TXN-2023-10-14-014",
      type: "fee",
      amount: 15.0,
      fee: 0,
      status: "completed",
      date: "2023-10-14T09:30:00.000Z",
      customer: {
        name: "Marketplace",
        email: "admin@marketplace.com",
      },
      product: null,
      paymentMethod: "system",
    },
    {
      _id: "txn_15",
      transactionId: "TXN-2023-10-15-015",
      type: "purchase",
      amount: 89.99,
      fee: 2.7,
      status: "completed",
      date: "2023-10-15T13:40:00.000Z",
      customer: {
        name: "Jennifer Lee",
        email: "jennifer.l@example.com",
      },
      product: {
        name: "Wireless Keyboard",
        id: "prod_008",
      },
      paymentMethod: "credit_card",
    },
    {
      _id: "txn_16",
      transactionId: "TXN-2023-10-16-016",
      type: "deposit",
      amount: 500.0,
      fee: 0,
      status: "completed",
      date: "2023-10-16T15:15:00.000Z",
      customer: {
        name: "Seller Account",
        email: "seller@example.com",
      },
      product: null,
      paymentMethod: "bank_transfer",
    },
    {
      _id: "txn_17",
      transactionId: "TXN-2023-10-17-017",
      type: "purchase",
      amount: 399.99,
      fee: 11.99,
      status: "failed",
      date: "2023-10-17T10:50:00.000Z",
      customer: {
        name: "Thomas Anderson",
        email: "thomas.a@example.com",
      },
      product: {
        name: "Smartphone",
        id: "prod_009",
      },
      paymentMethod: "credit_card",
    },
    {
      _id: "txn_18",
      transactionId: "TXN-2023-10-18-018",
      type: "refund",
      amount: 149.99,
      fee: 0,
      status: "completed",
      date: "2023-10-18T12:25:00.000Z",
      customer: {
        name: "Emily Davis",
        email: "emily.d@example.com",
      },
      product: {
        name: "External Hard Drive",
        id: "prod_005",
      },
      paymentMethod: "paypal",
    },
    {
      _id: "txn_19",
      transactionId: "TXN-2023-10-19-019",
      type: "purchase",
      amount: 249.99,
      fee: 7.49,
      status: "completed",
      date: "2023-10-19T14:10:00.000Z",
      customer: {
        name: "Daniel White",
        email: "daniel.w@example.com",
      },
      product: {
        name: "Noise-Cancelling Headphones",
        id: "prod_010",
      },
      paymentMethod: "credit_card",
    },
    {
      _id: "txn_20",
      transactionId: "TXN-2023-10-20-020",
      type: "withdrawal",
      amount: 1200.0,
      fee: 12.0,
      status: "completed",
      date: "2023-10-20T16:30:00.000Z",
      customer: {
        name: "Seller Account",
        email: "seller@example.com",
      },
      product: null,
      paymentMethod: "bank_transfer",
    },
  ]